// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Doc = 1,
  Null = 2,
  Bool = 3,
  Num = 4,
  Char = 5,
  Typ = 8,
  Idxr = 11,
  Keyr = 14,
  Tag = 15,
  Sym = 16,
  Tupl = 19
